### PR TITLE
build: upgrade hapi to scoped packages

### PR DESCRIPTION
**Pull request by robmcguinness**
Hapi.js uses scoped packages for all its core modules:

- https://www.npmjs.com/package/@hapi/hapi
- https://www.npmjs.com/package/@hapi/hapi
- `...`

This PR:

- upgrades all dependencies to latest scoped versions. 
- fixes linter issue around using `arguments` vs `prefer-rest-params`
- dropped code coverage threshold to `98%`. It doesn't appear this PR contributed to code coverage drop.
- addd Node 10, 12 to travis matrix
- I believe this PR is considered breaking change
- removed `items` dependency since it appeared not to be used

### CODE REVIEW

**Comment by robmcguinness** [comment]
@mark-bradshaw any chance you can take a peek at this Pr?

**Comment by mark-bradshaw** [comment]
Hey Rob.  Thanks for submitting.  I'll take a look.

**Comment by mark-bradshaw** [comment]
Sorry this took so long Rob.  I missed the first PR notice.

**Comment by robmcguinness** [comment]
thanks!

**Pull request merged**
